Description: '

  This template deploys base resources for OpenpayWeb

  '
Outputs:
  DeployRole:
    Description: DeployRole
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-DeployRole
    Value:
      Fn::GetAtt:
      - DeployRole
      - Outputs.RoleArn
Parameters:
  S3BucketName:
    Description: Name of S3 Bucket to allow access to
    Type: String
Resources:
  DeployRole:
    Properties:
      Parameters:
        S3BucketName:
          Ref: S3BucketName
      TemplateURL: https://s3.amazonaws.com/openpay-nonprod-cloudformation-ap-southeast-2/OpenpayWeb/cd7c2c77517ca3c25b444baddf1c05ac.template
    Type: AWS::CloudFormation::Stack
